services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3002:3000"
    environment:
      BACKEND_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      IN_QUEUE: fila.notificacao.entrada.gabrielcoimbra
      OUT_QUEUE: fila.notificacao.status.gabrielcoimbra

volumes:
  rabbitmq_data:
